import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";
import Searchbar from "../components/Searchbar";
import ListOfDorms from "../components/ListOfDorms";

const bearAsciiArt = `           (o\\---/o)  
            ( . . )                  .(  
   ________ ( (T) )                 /%/\\  
 o|               /                (%(%))
  |  ____________/                .-'..'-.
  |||         |||                '-'.'''-'     
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="theme-color" content="#4285f4" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}

      <main className={styles.main}>
        <Searchbar />
        <div className={styles.container}>
          <ListOfDorms dorms={["Dorm 1", "Dorm 2", "Dorm 3"]} />
        </div>
      </main>
    </>
  );
};

export default Home;
